#!/bin/bash
#

PYTHON=".venv/bin/python3"
$PYTHON <<EOF
#!/usr/bin/env python3

import json

import jinja2

env = jinja2.Environment(
    variable_start_string = "\VAR{",
    variable_end_string = "}",
    loader=jinja2.FileSystemLoader(['.']),
    # loader=jinja2.FileSystemLoader(['.', 'templates']),
)

with open("data.json", "r") as fh:
    data = json.loads(fh.read())

template = env.get_template("resume.tex.j2")
with open("resume.tex", "w") as fh:
    fh.write(template.render(**data))
EOF

