#!/bin/bash
#

PYTHON=".venv/bin/python3"
$PYTHON <<EOF
#!/usr/bin/env python3

import json

import jinja2
import yaml

env = jinja2.Environment(
    block_start_string="\BLOCK{",
    block_end_string="}",
    variable_start_string = "\VAR{",
    variable_end_string = "}",
    # loader=jinja2.FileSystemLoader(['.']),
    loader=jinja2.FileSystemLoader(['.', 'templates']),
)

with open("data.yaml", "r") as fh:
    data = yaml.safe_load(fh.read())

template = env.get_template("resume.tex.j2")
with open("resume.tex", "w") as fh:
    fh.write(template.render(**data))
EOF

